name: Wine Ubuntu CI

on:
  schedule:
    - cron:  '25 9,21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Compilation
        run: |
          sudo dpkg --add-architecture i386 && sudo apt update
          sudo apt install aptitude
          sudo aptitude remove -y '?narrow(?installed,?version(deb.sury.org))'
          cd wine-tkg-git/wine-tkg-git

          [ -f "./wine-tkg-userpatches/"*] && rm "./wine-tkg-userpatches/"*".mypatch"
          patches=("silence-sc-unsupported-os")
          for file in "${patches[@]}"; do
              cp "../../patches/wine/$file.patch" "./wine-tkg-userpatches/${file%.patch}.mypatch"
          done

          sed -i 's/wayland_driver="false"/wayland_driver="true"/' customization.cfg

          sed -i 's/use_staging="true"/use_staging="false"/' customization.cfg
          #sed -i 's/use_ntsync="false"/use_ntsync="true"/' customization.cfg
          #sed -i 's/use_esync="true"/use_esync="false"/' customization.cfg
          #sed -i 's/use_fsync="true"/use_fsync="false"/' customization.cfg

          sed -i 's/staging_userargs="-W ntdll-NtAlertThreadByThreadId"/staging_userargs="-W ntdll-NtAlertThreadByThreadId -W ntdll-ForceBottomUpAlloc"/' ./wine-tkg-profiles/advanced-customization.cfg

          sed -i 's/_NOLIB32="false"/_NOLIB32="wow64"/' wine-tkg-profiles/advanced-customization.cfg
          echo '_ci_build="true"' >> customization.cfg
          touch tarplz
          yes|./non-makepkg-build.sh
      - name: Archive the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wine-tkg-build
          path: wine-tkg-git/non-makepkg-builds
